server:
  port: 8088
  servlet:
    session:
      timeout: 1800s

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 3600s
  main:
    banner-mode: console
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    name: datasource
    url: jdbc:mysql://localhost:3306/springboot2019?serverTimezone=GMT%2b8
    username: root
    password: 970512
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
#    druid:
#      test-on-borrow: false
#      test-while-idle: true
#      test-on-return: false
#      validation-query: SELECT 1

  application:
    name: mq-producer
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: admin

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  path: /base-web-log

# 应用信息
app:
  app-name: app
  app-host: http://app.com
  allow-generate-api: true
  allow-cross-domain-access: true
  # 开发dev 测试test  生产 master
  env: dev

# 对象存储配置
object-storage:
  accessKeyId:
  accessKeySecret:
  upload-endpoint:
  download-endpoint:
  bucketName:
  # 下载地址的有效时长，单位为ms，默认为半小时（非必填）
  download-url-expiration: 1800000
  #样式（非必填）
#  styleName: resize,h_250

# 图片尺寸限制
img:
  width: 2000
  height: 2000