server:
  port: 8088
#  session-timeout: 1800

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
#    pool:
#      max-active: 8
#      max-wait: 1
#      max-idle: 8
#      min-idle: 0
#    timeout: 3600
  main:
    banner-mode: console
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#    multipart:
#      enabled: true
#      max-file-size: 1024Mb
#      max-request-size: 1024Mb
  datasource:
    name: datasource
#    initialize: false
    url: jdbc:mysql://localhost:3306/springboot2019?serverTimezone=UTC
    username: root
    password: 970512
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  path: /base-web-log
